services:
  # Backend API Service
  - type: web
    name: todoapp-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        fromDatabase:
          name: todoapp-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

  # Frontend React App Service  
  - type: web
    name: todoapp-frontend
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_SERVER_URL
        value: https://todoapp-api.onrender.com/api

databases:
  - name: todoapp-db
    databaseName: todo
    user: todoapp
